-- Your SQL goes here
CREATE TABLE commands (
    uuid VARCHAR(36) NOT NULL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hearts INTEGER NOT NULL DEFAULT 0,
    description VARCHAR(255) NOT NULL,
    command VARCHAR(255) NOT NULL,
    book VARCHAR(36) NOT NULL
);

CREATE TABLE books (
    uuid VARCHAR(36) NOT NULL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hearts INTEGER NOT NULL DEFAULT 0,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL
);
